import type { Metadata } from 'next'
import '../styles/globals.scss'
import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import { firaFont } from './fonts'

export const metadata: Metadata = {
  title: 'Ecosolution',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={firaFont.className}>
        <div className='container'>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
